#!/bin/bash

yarn workspace @redhatinsights/backstage-plugin-ai-search-frontend export-dynamic
cd plugins/ai-search-frontend/
rm *.tgz
npm pack ./dist-dynamic
cd ../..
mv plugins/ai-search-frontend/*.tgz .
sha256sum *.tgz | awk '{print $1}' | xxd -r -p | base64